# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocloud < Formula
  desc "NoCloud Platform CLI"
  homepage "https://github.com/slntopp/nocloud"
  version "0.2.2-r8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r8/nocloud_0.2.2-r8_Darwin_arm64.tar.gz"
      sha256 "abd1a4ec50be0097079ac311150d81d106f43fd7c004149506f7a1af677a3968"

      def install
        bin.install "nocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r8/nocloud_0.2.2-r8_Darwin_x86_64.tar.gz"
      sha256 "f33be4e0636b9e6616141887dbf3c924244190a39187bc8d98eee0054a7ce45d"

      def install
        bin.install "nocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r8/nocloud_0.2.2-r8_Linux_arm64.tar.gz"
      sha256 "86d3a7604e9e1b347bb81e71fecf2fbd955cada083b9a84a8d82b8733299a9bf"

      def install
        bin.install "nocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r8/nocloud_0.2.2-r8_Linux_x86_64.tar.gz"
      sha256 "a725579a4b35122adfe1849b84c8a2bd1d430ce139e053a27cbbffda592376d6"

      def install
        bin.install "nocloud"
      end
    end
  end

  def caveats; <<~EOS
    Start with nocloud help login ;)
  EOS
  end
end
