# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocloud < Formula
  desc "NoCloud Platform CLI"
  homepage "https://github.com/slntopp/nocloud"
  version "0.2.2-r4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r4/nocloud_0.2.2-r4_Darwin_x86_64.tar.gz"
      sha256 "b82f2f0ef00d1d533fc3a2964f6e0e0c4514162b8e18aa5959e3766303452132"

      def install
        bin.install "nocloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r4/nocloud_0.2.2-r4_Darwin_arm64.tar.gz"
      sha256 "2abdf6929c10a1b311d3f710849d1492468ac5f9142a0dcedf699fb9bfc9a383"

      def install
        bin.install "nocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r4/nocloud_0.2.2-r4_Linux_arm64.tar.gz"
      sha256 "bb2a2b0b101a67bf264c2d081a002e007df39de60f1680f95992a5e99a182a31"

      def install
        bin.install "nocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r4/nocloud_0.2.2-r4_Linux_x86_64.tar.gz"
      sha256 "20b0dd7ca18deb53a26f9de0a47c3409b95841f6fa02879332c05539295f8afb"

      def install
        bin.install "nocloud"
      end
    end
  end

  def caveats; <<~EOS
    Start with nocloud help login ;)
  EOS
  end
end
