# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nocloud < Formula
  desc "NoCloud Platform CLI"
  homepage "https://github.com/slntopp/nocloud"
  version "0.2.2-r2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r2/nocloud_0.2.2-r2_Darwin_x86_64.tar.gz"
      sha256 "3fbc24b864d28839910de7abc832678ed43d1ad4545e4b0d8062abfb55a2cfc5"

      def install
        bin.install "nocloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r2/nocloud_0.2.2-r2_Darwin_arm64.tar.gz"
      sha256 "9495afde479547b3823a68c173c25f3a3c6a6b443527d8ca2642807c69c49f8f"

      def install
        bin.install "nocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r2/nocloud_0.2.2-r2_Linux_x86_64.tar.gz"
      sha256 "cdda7dd6fa4163ce87454d91f128902af8280dfc655f8d1e6f78743f27679a10"

      def install
        bin.install "nocloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slntopp/nocloud-cli/releases/download/v0.2.2-r2/nocloud_0.2.2-r2_Linux_arm64.tar.gz"
      sha256 "b6fcca2d5c2b026f3ba2a4fecb7d7e2f2d566d56a273cd504dfbf07ab02c99b2"

      def install
        bin.install "nocloud"
      end
    end
  end

  def caveats; <<~EOS
    Start with nocloud help login ;)
  EOS
  end
end
